### ISSUE TITLE
Double check footer / and that body is there....

### ISSUE THREAD

**Issue by sheriffderek** [TareUhhhhhh/pe-projects#2]
https://github.com/TareUhhhhhh/pe-projects/blob/b0c8cfa3b163226656f5eafeb182e3e35d96b485/index.php#L21

**Comment by TareUhhhhhh** [comment]
Updated with about and contact section.

**Comment by TareUhhhhhh** [comment]
Body element was missing entirely! Added to the header (opening) and index (closing).
